// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzztbocykokeqqmnccmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6enRib2N5a29rZXFxbW5jY215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTc2NTgsImV4cCI6MjA1ODgzMzY1OH0.OSE-m3gXPF-NoEaw-N6O_AR2iqv-2cZ97UZy47FFEH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);